### PR TITLE
Fix pdf & implement round_to for cdf() -> calculate_cdf() & add cdf attrib

### PR DESCRIPTION
**Pull request by mhdzumair**
In this PR i fixed the pdf and add the round_to arg for calculate_cdf() this is the new name for calculating cdf. and also create base attribute as self.cdf so dont use cdf as a function on subclasses.

### CODE REVIEW

**Comment by mhdzumair** [comment]
bro please accept this pr before midnight 12

**Review by hot9cups — APPROVED** [review]
Fantastic! I love you how you always end up doing more than what was promised! Loved the changes to code style, and the bug fixes, as well as everything else! I've added the hacktoberfest-accepted tag as well so I hope you complete the Hacktoberfest event!

Also, I read your comment in the other PR, and to reply to that, yes I did mean dropdown list. :)

Thanks a lot for your contribution mate! Excellent job!

**Comment by mhdzumair** [comment]
> Fantastic! I love you how you always end up doing more than what was promised! Loved the changes to code style, and the bug fixes, as well as everything else! I've added the hacktoberfest-accepted tag as well so I hope you complete the Hacktoberfest event!
> 
> Also, I read your comment in the other PR, and to reply to that, yes I did mean dropdown list. :)
> 
> Thanks a lot for your contribution mate! Excellent job!

bro so far i create  7 PRs but when it will review by hacktober  team? my first pr time running as mature in: 9d:1h:41m:43s

**Comment by hot9cups** [comment]
@mhdzumair The review isn't by hacktoberfest team, it is by the repository maintainers, for example me. I've already reviewed all the PRs you made here and accepted all of them. Secondly, any PRs you made to non-spam repos(Like this one) will definitely count so there's no need to worry about hacktoberfest disqualifying your PRs. 

Now you just have to wait for the timer to finish. Ie, after 9 days your PR becomes mature :)

**Comment by hot9cups** [comment]
I checked your profile, I see you completed your 4 PRs on 27th October.

Last year people who completed their PRs in the 3rd week of October got the prize too, this year the number of shirts increased from 50k to 75k, so I think you still have a great chance bro :)

**Comment by mhdzumair** [comment]
> @mhdzumair The review isn't by hacktoberfest team, it is by the repository maintainers, for example me. I've already reviewed all the PRs you made here and accepted all of them. Secondly, any PRs you made to non-spam repos(Like this one) will definitely count so there's no need to worry about hacktoberfest disqualifying your PRs.
> 
> Now you just have to wait for the timer to finish. Ie, after 9 days your PR becomes mature :)

Ohh, thanks for your information bro. I thought hacktober team need to review or something and also i pushed my first 4 pr to funny repo. in that repo we can push our mini projects haha. So i thought it will not count as pr by hacktober team.

**Comment by mhdzumair** [comment]
> I checked your profile, I see you completed your 4 PRs on 27th October.
> 
> Last year people who completed their PRs in the 3rd week of October got the prize too, this year the number of shirts increased from 50k to 75k, so I think you still have a great chance bro :)

Yeah, let see what happen after date period end. I'm glad to work with your project.

**Comment by hot9cups** [comment]
@mhdzumair Sometimes, funny repos (Spam repos) can be banned by Hacktoberfest thereby making all PRs submitted to it invalid. However, in your case I don't think it was a spam repo so you should hopefully be fine! I hope you win the prize and hope to work with you in the future too! (I'll be shamelessly pinging you again in the future whenever I run into rounding issues hahah :P)

Also, you can connect with me on discord as well :)
My discord id is hot9cups#3125

Cheers bro

**Comment by hot9cups** [comment]
@mhdzumair Seeing how helpful you have been in the developing of the library, not only improving the code but also helping others in their PRs, I would like to ask you if you would like to become the co-owner of the library with me? Because you've been working so earnestly and diligently on this, I think you deserve a lot more credit :)

If so, can we connect on discord(or mail: hot9cups@yahoo.in) to discuss this further ? :)

**Pull request merged**
