### PR TITLE
Cumulative distribution function for Gaussian distribution 

### PR DESCRIPTION
**Pull request by RimorRes**
### Added 
- [x] Cumulative distribution function for Gaussian distribution ✨ 
- [x] Test for Gaussian distribution CDF ✅ 

### Fixed
- [x] Linter warnings 🚨

### CODE REVIEW

**Comment by RimorRes** [comment]
Solution to #38

**Review by hot9cups — APPROVED** [review]
@RimorRes This is good, a numerical approximation of the CDF. I think that's about as close as we can get. There's just one more thing I'll need you to do before I can merge this, could you also go ahead and update USAGE.md to reflect the changes you've made?

**Comment by RimorRes** [comment]
Done!
I updated `USAGE.md` to include the changes I made to the Gaussian distribution class.

**Review by hot9cups — APPROVED** [review]
Looks good

**Comment by hot9cups** [comment]
@RimorRes Thanks a ton for your contribution to the library! Good job! If you find the repo useful in your work in the future, feel free to star it :) and if you know someone else who it might be of use to, you know what to do :P

Thanks once again! I'll be sure to include you as a contributor when I release the next version of the library :)
Cheers!

**Comment by RimorRes** [comment]
No problem, happy I could be of service!
Good luck with your future work!

**Pull request merged**
