### PR TITLE
Rewrite read_data_file() to take sep

### PR DESCRIPTION
**Pull request by basil08**
I know you have assigned this to someone. But I already wrote the code yesternight. 

Please keep this.
You can choose whichever version to merge.

I have tested this function. Works for all edge cases.

This is for #8

### CODE REVIEW

**Comment by basil08** [comment]
There is one whitespace issue. Please see into it.

**Review by hot9cups — APPROVED** [review]
This looks quite good, though yes there's already someone else who was assigned to it and is working on it. I'll get back to this in case the assignee isn't able to complete the task/the code quality isn't as good as this :)
Thanks.

**Comment by hot9cups** [comment]
Thanks for this, but @errpv78 has already finished working on it and I've merged his changes. He did a really good job there, and I'm going to have to close this PR now. Thanks both of you!

**Comment by errpv78** [comment]
@hot9cups you're welcome, and I would love to do more work with you in the future.

**Pull request closed without merging**
