### PR TITLE
Refactor read data file

### PR DESCRIPTION
**Pull request by fibonacci-spirals**

### CODE REVIEW

**Review by mhdzumair — CHANGES_REQUESTED** [review]
Hey bro, In Unit Test

    def test_stdevcalculation(self):
        self.uniform.calculate_stdev()
        self.assertEqual(round(self.uniform.stdev, 2),
                         2.89,
                         'calculated standard deviation incorrect')   
with round_to arg you can round the output value for pdf. so dont call round method externally. 
You can change the code to

    def test_stdevcalculation(self):
        self.assertEqual(self.uniform.calculate_stdev(round_to=2),
                         2.89,
                         'calculated standard deviation incorrect')

**Comment by fibonacci-spirals** [comment]
> Hey bro, In Unit Test
> 
> ```
> def test_stdevcalculation(self):
>     self.uniform.calculate_stdev()
>     self.assertEqual(round(self.uniform.stdev, 2),
>                      2.89,
>                      'calculated standard deviation incorrect')   
> ```
> 
> with round_to arg you can round the output value for pdf. So don't call round method externally.
The implementation is similar to the std_dev calculation in Gaussian, where the returned std_dev is rounded to 2, but the value stored in the class object is not rounded. I will instead compare it with the returned value in the test.

**Comment by hot9cups** [comment]
@mhdzumair could you confirm whether the changes fibonacci-spirals made are okay, or whether it requires further changes?

**Comment by mhdzumair** [comment]
Yeah, sure. I'm checking the changes

**Comment by mhdzumair** [comment]
> The implementation is similar to the std_dev calculation in Gaussian, where the returned std_dev is rounded to 2, but the value stored in the class object is not rounded. I will instead compare it with the returned value in the test.

Yes you can compare the return value because it also round it to 2

**Review by hot9cups — CHANGES_REQUESTED** [review]
Yeah Zumair's right. I think it's similar to the Gaussian class test,
```
self.assertEqual(self.gaussian.calculate_stdev(),
                         92.87, 'sample standard deviation incorrect')
```
the returned value, if you look at the source code, is already rounded. You can either store the returned value in a variable and compare it, or do it like in the code snippet above, instead of accessing the attribute self.uniform.stdev

So that's the change you need to make now.

I think going forward, I'm tempted to add accessor methods for mean and std but that's not very Pythonic, so I'll have to think something about that but that's another issue.

As soon as you make the required changes, I'll be happy to merge :)

Oh also don't forget to make the changes you made in the earlier PR(throwing an error in init for low == high) here as well, otherwise merging this will effectively negate the changes. Alternatively, refreshing your fork is perhaps a better idea.

**Review by mhdzumair — CHANGES_REQUESTED** [review]
Another thing is refactoring the load data. the load_file_name() function is never used again and again so i think it should not be a function. you can create dictonary and map the matching file inside the read_data_file() method. and also since your new function not using any self attribute you made the function outside the class that also not good. 

in  read_data_file() function add this changes.

    file_name_map = {
        'demo_gaussian_data': 'numbers',
        'demo_binomial_data': 'numbers_binomial',
        'demo_exponential_data': 'numbers_exponential',
        'demo_gamma_data': 'numbers_gamma',
        'demo_uniform_data': 'numbers_uniform',
        'demo_bernoulli_data': 'numbers_bernoulli'
    }
    if file_name in file_name_map:
        dirname = Path(__file__).parent.parent.absolute()
        file_name = str(Path(dirname, 'probdists/' + file_name_map[file_name] + '.txt'))

remove your new function and these line

        file_path = load_file_name(file_name)
        file_name = str(file_path)

**Review by hot9cups — APPROVED** [review]
LGTM! @mhdzumair anything to add?

**Review by mhdzumair — APPROVED** [review]

**Comment by mhdzumair** [comment]
bro I think it is ok now

**Review by hot9cups — COMMENTED** [review]
Great. @fibonacci-spirals Thanks a lot for working on this, we'd been looking for refactoring of this for sometime now and I'm glad someone finally got to it! That was pretty nicely done and I appreciate your patience for sticking around till the end! 

If you find the library useful in your work, feel free to star it :)
Thanks once again for contributing to the package!!

**Comment by fibonacci-spirals** [comment]
> Great. @fibonacci-spirals Thanks a lot for working on this, we'd been looking for refactoring of this for sometime now and I'm glad someone finally got to it! That was pretty nicely done and I appreciate your patience for sticking around till the end!
> 
> If you find the library useful in your work, feel free to star it :)
> Thanks once again for contributing to the package!!

Of course, I really enjoyed contributing too! Open source was pretty intimidating to me earlier, but you were very helpful in getting me through any roadblocks and I really appreciate it!

**Pull request merged**
