### PR TITLE
Tests issues fixed

### PR DESCRIPTION
**Pull request by errpv78**
1. All test files moved to probdists subdirectory.
2. All paths updated accordingly.
3. Filename converted to a string to accommodate POSIX path change in case of gamma and other file names.
4. All tests run successfully.

### CODE REVIEW

**Comment by errpv78** [comment]
So again there is an import issue with pandas, it says missing xlrd. For pandas are there any specific changes that are required to make in requirements or any other file?

**Comment by hot9cups** [comment]
@errpv78 I already added pandas to requirements.txt, there seems to be a failure for xlrd now.
You'll have to tell me all the dependencies needed, which I'll have to add to requirements.txt
You'll (painfully I know T.T) then have to create a fresh PR to run the updated tests.
I suggest you create a virtual environment on your pc, try running the code and make a list of the libraries you had to install to get your code running.

**Comment by errpv78** [comment]
Okay I'll make a fresh list of required libraries.

**Comment by errpv78** [comment]
Okay I have made list of all the requirements:
certifi==2020.6.20
cycler==0.10.0
kiwisolver==1.3.0
matplotlib==3.3.2
numpy==1.19.3
pandas==1.1.3
Pillow==8.0.1
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
six==1.15.0
xlrd==1.2.0

Update the requirements and then I'll make the pr.

**Comment by hot9cups** [comment]
@errpv78 Done!

**Comment by hot9cups** [comment]
@errpv78 any updates?

**Comment by errpv78** [comment]
Okay so I'm closing this one

**Pull request closed without merging**
