### PR TITLE
Abstract methods added to base distribution class

### PR DESCRIPTION
**Pull request by zmunro**
- Organized the test files into a separate folder
- Made a formal inheritance from the base distribution class to the other distribution classes
- added dummy functions that people can add to for distributions that did not have the abstract methods of the base class implemented
- fixed the gamma class as it was very different from the others in how it initialized itself

### CODE REVIEW

**Review by hot9cups — COMMENTED** [review]
Hey @zmunro ! Thanks for taking the time to contribute to the project.

Well there's a couple of changes which are good, and a couple of them which I'm not too keen about. I like the addition of abstract methods. Also appreciate the fixing of typos. I'm not quite sure about replacing single quotes with double quotes, as well as the changes made to the Gamma class. A large portion of read_data_file()'s code was chunked, but there was no replacement logic added. Also, the changes seem to have broken the code as all tests now fail. 

Finally, do create an issue first and have a discussion with me before proceeding to make a PR the next time, as it helps direct the code in a more reasonable manner. I look forward to having you back and getting this to work :)

**Comment by zmunro** [comment]
@hot9cups Thanks for taking a look at it!
The change from single quotes to double quotes was done by my python formatter [Black](https://black.readthedocs.io/en/stable/). I can change that back if wanted but up to you.

No functionality of `GeneralDistribution.py` was lost. I replaced a lot of code in that classe's `read_data_file()` function since it didn't make a lot of sense. It took in a file name as an argument, but it wasn't actually a filename but something that got mapped to a filepath. I figured it made more sense to just pass in a file path and then people could more easily add their own files.

The only reason that the tests failed should be because I started using the scipy package but forgot to add it to the requirements.txt file, which should be fixed now.

The reason the Gamma class was changed so much was because it diverged from all the other classes in how it handled initialization, and a major benefit of using inheritance is being able to rely on child classes to have reliable and standard behavior.

**Comment by zmunro** [comment]
@hot9cups I have all the tests and linting working. Something else that I changed in this is that I removed the `round_to` argument to all functions that had it. The client should be deciding whether to round at all instead of having to pass it as an argument. And having that as an argument on every function just adds unnecessary bloat I think.

**Comment by hot9cups** [comment]
Hey @zmunro . Thanks again for taking the time to contribute!

Well like I mentioned in my last comment, I still feel these discussions would have been better suited in an issue than here in the PR. But let's get to it now that we're here.

> I replaced a lot of code in that classe's read_data_file() function since it didn't make a lot of sense. 

That's a perfect scenario for opening an issue. I'd have rather appreciated it a lot more had you discussed it with me before proceeding to make changes for I'd have been able to explain it to you in greater depth/understand your POV. Secondly and more importantly, there was someone else who was already working on it. That's a lot of effort wasted, you see?

>It took in a file name as an argument, but it wasn't actually a filename but something that got mapped to a filepath. 

To clear your confusion about the read_data_file(), this isn't a library that's intended to be cloned from github and be used. It's been released to PyPi and that is where I'd expect its audience to obtain the library from. Then there's also some demo data files that I originally shipped with the package. To actually open these demo files, you'd have to pass the path of the directory where your package manager installs libraries, instead of a mere 'demo_files/data.txt' or 'fixtures/data.txt' because the latter would look for the a 'demo_files' folder in the directory from where the client code is being executed, not where the source code lies. Expecting the user to do all that was unreasonable, which was why decided to ask them to pass 'demo_xyz_file' when they wanted the demo files. But do note that it also works if you pass in a regular file path.
read_data_file() either takes in a file path to the user's data OR a string to map it to the internal demo data files. If you inspect the code further, you'll see it works for both cases.

>  I figured it made more sense to just pass in a file path and then people could more easily add their own files.

It already allows the user to pass in a file path. But yes, it did make more sense to refactor the method though. But we had an issue open for that and someone was working on it already. 

> Gamma class diverged from all other classes.

True. For most of the other classes, there was a `replace_stats_with_data()` function which would fit the parameters of the distribution to the user's data instead of the defaults that the object is loaded with. However, it was a little more difficult to write the method for certain classes than the others. Now the Gamma distribution came in right during the wee end of Hacktoberfest, so we decided to merge it since it had the functionality we needed, the refactoring we kept for later.
So yes, the class needs refactoring, in that the logic from the `__init__()` ought to be shifted to the `replace_stats_with_data()`, but what I'm afraid you've done is completely shun that part off.

Finally about the round_to, we originally had it the way you suggest. Then we decided to add the round_to because most times the numbers aren't going to be clean when working with probability distributions and so the usage of round() became so common that we decided to just embed it. We kept in a default of 2 places, maybe 5 was more reasonable. I'm still not very keen on reverting the work we did and getting rid of it, but the point you make is fair.
In which case, I think it's probably a better solution to have the user define a mode at the very start - round on/off.

I appreciate the time and effort you put into this and it would be quite painful for this to not bare fruit, I just wish you would have opened an issue first so we could have saved half the effort you're putting in here. Appreciate it, which is why I'd still like to retain a few of the changes you've proposed.

So I think the revised changes we want to make going forward would be -
- Addition of abstract methods the way you did.
- Implementation of a rounding_mode that's set by the user in the beginning, preventing rounding in off mode, and rounding to a default number of places(customisable) while it's in the on mode. 
- Refactoring of Gamma class (ie without losing current functionality).
- I guess we could change the single quotes to double quotes though that would be changing for the sake of it, since pylint and flake8 didn't seem to complain about it and we've tried maintaining uniformity as much as possible.

A lot of the code I would agree might seem clumsy, the library's fairly new and again a major part of it was built during hacktoberfest. Still early days.

Thanks once again for your interest in the project. 
I look forward to your revised changes.

**Pull request closed without merging**
