### PR TITLE
round_to: implement round function internally for pdf

### PR DESCRIPTION
**Pull request by mhdzumair**
Create a pdf attribute in general Distribution. Refactor pdf method to calculate_pdf method & add round_to arg.
This PR is related to  #32  Issue.

### CODE REVIEW

**Review by hot9cups — APPROVED** [review]
@mhdzumair This looks good. One thing I'd like you to add is update the USAGE.md file to reflect the changes. Apart from that, everything is perfect. Once you make the change I'll be happy to merge :)

**Comment by mhdzumair** [comment]
> 
> 
> @mhdzumair This looks good. One thing I'd like you to add is update the USAGE.md file to reflect the changes. Apart from that, everything is perfect. Once you make the change I'll be happy to merge :)

I already done that part. Check this one [USAGE: update docs for pdf() -> calculate_pdf() with round_to arg](https://github.com/hot9cups/probdists/pull/33/commits/cf9bf6feb8ddf8948ee88db827e55ba33b24d8ef)

**Review by hot9cups — APPROVED** [review]
@mhdzumair Ah, for some reason I couldn't find the file when I was reviewing last time. I guess I've been awake for too long. My bad, apologies for that. Great work once again, just like your last PR :) 
Thank you for the contribution! This was great!

**Comment by mhdzumair** [comment]
You're welcome. My pleasure to work on your project.

**Comment by hot9cups** [comment]
@mhdzumair Hello again! We had a new class added, Bernoulli Distribution! As usual, the rounding methods and style was nowhere as good as yours. Are you willing to take it up :)

If so, let me know by creating an issue and I'll assign it to you right away.
I feel like I'm going to be coming to you a lot often whenever we have new classes being added!

(Ofcourse, if you're busy with other work, let me know about that too. We can do it later in that case :) )

**Comment by mhdzumair** [comment]
My pleasure to work with you. I also think about cdf method that also needs to add round.

**Comment by hot9cups** [comment]
Yep! That's right 👍

**Comment by mhdzumair** [comment]
> Yep! That's right +1

ok bro I will do that now.

**Comment by hot9cups** [comment]
Thank you bro ❤️

**Pull request merged**
