### PR TITLE
Add Bernoulli Distribution with unittest and usage

### PR DESCRIPTION
**Pull request by basil08**
Added Bernoulli with its unittest and usage.

And few minor fixes.

### CODE REVIEW

**Comment by basil08** [comment]
@hot9cups I have no idea what is wrong with `from probdists import Bernoulli`.

And, there are couple of trailing whitespaces, I'll fix them later.

**Comment by hot9cups** [comment]
The import is failing probably because you haven't changed `__init__.py` suitably.

Also, there's going to a change with the sample data files path and the way they're tested in the unittests, which should hopefully be merged into the repo by tomorrow. Therefore please wait till that's done(I'll ping you), then refresh your fork of the repo and create a fresh PR.

**Comment by hot9cups** [comment]
> Therefore please wait till that's done(I'll ping you), then refresh your fork of the repo and create a fresh PR.
@basil08 Everything's been resolved now with the codebase, so you can go ahead and continue working :)

**Comment by hot9cups** [comment]
Are you working on this? I've added additional github actions and tests which doesn't work on PRs opened before the addition took place. Request you to make a new PR.

**Pull request closed without merging**
