### PR TITLE
Read_data_file function updated

### PR DESCRIPTION
**Pull request by errpv78**
Features added:
1. Custom separator support for text files.
2. Reading data from CSV files (with default separator ',')
3. Reading data from excel file with supported formats (xls, xlsx, xlsm, xlsb, odf, ods and odt)

Changes and specifications:
1. For txt files default separator is blank space that will deal with space-separated or line separated numbers.
2. header parameter is only for excel files.
3. The extension of the file is identified first and then the process is initiated.
4. For CSV file separator is set to ','.
5. For excel files parameter of the header to mention from which row to start reading numbers is available. To start from row 0, the header is kept None as default.
6. Excel files are read using pandas. Update required in the project requirements, to include pandas too.
7. Lines are stripped to avoid endline space to get included in the next line number.
8. The number which is read as a string is first converted in float and then to int, to avoid errors due to float as a string to int direct conversions.
9. Exception handling used with appropriate warning in case of exceptions to handle strings or unwanted data in middle.

### CODE REVIEW

**Review by hot9cups — CHANGES_REQUESTED** [review]
This looks really good. Thanks for taking the time to contribute :) 

I've got a couple of questions.

What're the .idea/ files for? Not sure what they do here, could you explain?

Also, in the read_data_file() function, I see you're converting the data to ints from floats. This isn't always going to be true, the user might have files with float data, so let the dtype remain.

There's also a couple of code style issues that need resolving, which you can check out [here](https://app.codacy.com/gh/hot9cups/probdists/pullRequest?prid=6408573)

Lastly, would you also be able to include some tests in the [tests](https://github.com/hot9cups/probdists/blob/main/test.py) file, to check whether the function works properly with each type of file?

**Comment by errpv78** [comment]
I think idea files may be due to trial execution of the program on my side, I'll remove them.
Actually in the function earlier data was appended in a list as int, so I thought the list has to contain only int, but I'll change that and keep it float only, if I don't change it to float it will be string by default so as we are talking about numbers so float seems better.
I'll include the tests and also make the required changes to code style.

**Comment by hot9cups** [comment]
Oh, yeah you're right. The function earlier does seem to be appending ints, that's a nice catch. Unintended bug :D

Yes, I'm really happy with pretty much everything else, once the tests are ready and everything else is updated, I'd be glad to merge! Thanks a lot for the effort :)

**Comment by errpv78** [comment]
And I would also like to suggest either the test file should be moved to probdists directory or the paths of all text files that are stored in probdists should be changed by adding probdists/ to the paths, otherwise, there are chances of path error in the text files names.

**Comment by hot9cups** [comment]
@errpv78 That's a good suggestion. For now, I used a hacky approach and just added another .parent for obtaining the path so as to not break the test.py file. You're welcome to improve this if you like(in this PR or a separate one, I'm fine with either) :)

**Comment by errpv78** [comment]
Okay so I'll just add the tests and then we can finish this pr and later fix the paths thing in a new issue separately.

**Comment by hot9cups** [comment]
@errpv78 sounds good

**Comment by errpv78** [comment]
The tests have been included and I have also corrected the issue of the tests in this pr only as to run tests that were necessary. Some changes have been made in test.py and probdists/__init__.py to include tests. The code format is also corrected.

**Comment by hot9cups** [comment]
@errpv78 could you refresh your fork to the latest version of the repo, and then modify the test.py file? It's a little difficult to resolve the conflicts and I'm afraid I might end up breaking something

**Comment by errpv78** [comment]
Okay I'll do that

**Comment by errpv78** [comment]
I have tried to resolve conflicts here, can you confirm if that had worked?

**Comment by hot9cups** [comment]
@errpv78 The errors are caused because pandas wasn't a part of the library before this PR, so the linters weren't installing it before checking the code. I have updated the github action now to install pandas, but I'm afraid you'll have to make a new PR for the updated github actions to run. 

Secondly, don't forget you'll have to change the numbers sample data files' path, since right now they're located in the main directory, while in the code you proposed they'll have to be in the probdists directory so do take care of that. I see you didn't change the path of numbers_binomial.txt for example, and a few other .txt files so that will cause the code to fail.

Also, since you're now making a new PR, you might as well refresh your fork to the latest version and then submit the PR.
Cheers :)

**Comment by hot9cups** [comment]
@errpv78 Also, this PR is sort of an urgency because the other PRs made depend on it, so let me know if you could finish it by today, otherwise I'll have to let you wait for a couple of days :( and merge other PRs first, following which you'll be able to make your PR.

**Comment by errpv78** [comment]
Okay, I'll refresh the fork and make the second PR shortly. So in that, I have to update the changes that couldn't be merged until now and update paths of txt files. Anything else?

**Comment by hot9cups** [comment]
@errpv78 That's right. Just to reiterate, I'll list the changes again:
Update read_data_file(), update path of files, add the new data files you created, add the TestGeneraldistribution class you created in test.py,  update test.py to use your modified file paths. If you want, you can also include a note about the usage of the updated read_data_file() function in USAGE.md, or you can do that in another PR when you've got time.

I hope that makes it clear!

**Pull request closed without merging**
